name: sole_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter_modular: ^4.5.0
  mobx: ^2.0.6+1
  mobx_codegen: ^2.0.5+2
  flutter_mobx: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.8

flutter:
  uses-material-design: true
